[build.environment]
  NODE_VERSION = "22.18.0"
  # don't need playwright for docs build
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
  # docs site deployment requires generating llm text
  DOCS_ISLANDS_RELEASE = "1"
  DOCS_ISLANDS_MODE = "production"

[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm build && pnpm docs:build"

[[redirects]]
  from = "/docs-islands/*"
  to = "/:splat"
  status = 200

[[headers]]
  for = "/docs-islands/*/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable'''
