export {
  defineConfig,
  getActiveCheckerExtensions,
  getActiveCheckers,
  loadConfig,
  validateLiminaConfig,
  type BuiltinCheckerPreset,
  type BuiltinTaskName,
  type CheckerConfig,
  type CheckerExecutionKind,
  type CheckerPreset,
  type GraphConfig,
  type GraphRule,
  type GraphRuleDenyConfig,
  type GraphRuleDepDenyEntry,
  type GraphRuleNodeBuiltinDenyEntry,
  type GraphRuleRefDenyEntry,
  type GraphRuleWorkspaceDepDenyEntry,
  type LiminaCommand,
  type LiminaConfig,
  type LiminaConfigEnv,
  type LiminaConfigExport,
  type LiminaConfigFn,
  type LiminaConfigFnObject,
  type LiminaConfigFnPromise,
  type LoadConfigOptions,
  type PackageAttwCheckConfig,
  type PackageAttwProfile,
  type PackageBoundaryCheckConfig,
  type PackageCheckTarget,
  type PackageCheckTool,
  type PackageCheckToolSelection,
  type PackageChecksConfig,
  type PackagePublintCheckConfig,
  type PathsConfig,
  type PipelineStep,
  type ProofAllowlistEntry,
  type ProofConfig,
  type ResolvedCheckerConfig,
  type ResolvedLiminaConfig,
  type RuntimeEnvironment,
  type SharedLiminaConfig,
  type SourceBoundaryConfig,
} from './config';

export {
  LiminaFlowReporter,
  createLiminaFlowReporter,
  type LiminaFlowFailureOptions,
  type LiminaFlowMessageOptions,
  type LiminaFlowOutputOptions,
  type LiminaFlowReporterOptions,
  type LiminaFlowTask,
} from './flow';

export { runSourceCheck, type RunSourceCheckOptions } from './commands/source';
export {
  runCheckerBuild,
  runCheckerTypecheck,
  type RunCheckerBuildOptions,
  type RunCheckerBuildResult,
  type RunCheckerTypecheckOptions,
  type RunCheckerTypecheckResult,
  type TypecheckRunner,
  type TypecheckTarget,
  type TypecheckTargetResult,
} from './commands/typecheck';
export {
  collectTypecheckTargetProjectPaths,
  isOrdinaryTypecheckConfigPath,
  type CollectTypecheckTargetProjectPathsOptions,
  type CollectTypecheckTargetProjectPathsResult,
} from './tsconfig';
