blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://chat.vrite.cn
    about: Ask questions and discuss with other Docs Islands users in real time.
  - name: Questions & Discussions
    url: https://github.com/XiSenao/docs-islands/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
