name: "\U0001F680 New feature proposal"
description: Suggest an idea for this project
labels: ["pending triage"]
# type: Feature
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: "Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
      placeholder: As a developer using Docs Islands I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: "In module [xy] we could provide following implementation..."
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/XiSenao/docs-islands/blob/main/.github/CODE_OF_CONDUCT.md).
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/XiSenao/docs-islands/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://docs.senao.me/docs-islands/).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
