export {
  defineConfig,
  loadConfig,
  type BuiltinTaskName,
  type GraphConfig,
  type GraphForbiddenEdge,
  type GraphInferredProject,
  type GraphNodeBuiltinRule,
  type LatticeCommand,
  type LatticeConfig,
  type LatticeConfigEnv,
  type LatticeConfigExport,
  type LatticeConfigFn,
  type LatticeConfigFnObject,
  type LatticeConfigFnPromise,
  type LoadConfigOptions,
  type PackageAttwCheckConfig,
  type PackageAttwProfile,
  type PackageBoundaryCheckConfig,
  type PackageCheckTarget,
  type PackageCheckTool,
  type PackageCheckToolSelection,
  type PackageChecksConfig,
  type PackagePublintCheckConfig,
  type PathsConfig,
  type PipelineStep,
  type ProjectKindMatcher,
  type ProofAllowlistEntry,
  type ProofConfig,
  type ProofSidecarTarget,
  type ResolvedLatticeConfig,
  type RuntimeEnvironment,
  type WorkspaceConfig,
} from './config';

export {
  runTypecheck,
  type RunTypecheckOptions,
  type RunTypecheckResult,
  type TypecheckRunner,
  type TypecheckTarget,
  type TypecheckTargetResult,
} from './commands/typecheck';
export {
  collectTypecheckTargetProjectPaths,
  isOrdinaryTypecheckConfigPath,
  type CollectTypecheckTargetProjectPathsOptions,
  type CollectTypecheckTargetProjectPathsResult,
} from './tsconfig';
