export {
  defineConfig,
  getActiveCheckerExtensions,
  getActiveCheckers,
  loadConfig,
  validateLatticeConfig,
  type BuiltinCheckerPreset,
  type BuiltinTaskName,
  type CheckerConfig,
  type CheckerExecutionKind,
  type CheckerPreset,
  type GraphConfig,
  type GraphRule,
  type GraphRuleDenyConfig,
  type GraphRuleDepDenyEntry,
  type GraphRuleNodeBuiltinDenyEntry,
  type GraphRuleRefDenyEntry,
  type GraphRuleWorkspaceDepDenyEntry,
  type LatticeCommand,
  type LatticeConfig,
  type LatticeConfigEnv,
  type LatticeConfigExport,
  type LatticeConfigFn,
  type LatticeConfigFnObject,
  type LatticeConfigFnPromise,
  type LoadConfigOptions,
  type PackageAttwCheckConfig,
  type PackageAttwProfile,
  type PackageBoundaryCheckConfig,
  type PackageCheckTarget,
  type PackageCheckTool,
  type PackageCheckToolSelection,
  type PackageChecksConfig,
  type PackagePublintCheckConfig,
  type PathsConfig,
  type PipelineStep,
  type ProofAllowlistEntry,
  type ProofConfig,
  type ResolvedCheckerConfig,
  type ResolvedLatticeConfig,
  type RuntimeEnvironment,
  type SharedLatticeConfig,
  type SourceBoundaryConfig,
} from './config';

export {
  LatticeFlowReporter,
  createLatticeFlowReporter,
  type LatticeFlowFailureOptions,
  type LatticeFlowMessageOptions,
  type LatticeFlowOutputOptions,
  type LatticeFlowReporterOptions,
  type LatticeFlowTask,
} from './flow';

export { runSourceCheck, type RunSourceCheckOptions } from './commands/source';
export {
  runCheckerBuild,
  runCheckerTypecheck,
  type RunCheckerBuildOptions,
  type RunCheckerBuildResult,
  type RunCheckerTypecheckOptions,
  type RunCheckerTypecheckResult,
  type TypecheckRunner,
  type TypecheckTarget,
  type TypecheckTargetResult,
} from './commands/typecheck';
export {
  collectTypecheckTargetProjectPaths,
  isOrdinaryTypecheckConfigPath,
  type CollectTypecheckTargetProjectPathsOptions,
  type CollectTypecheckTargetProjectPathsResult,
} from './tsconfig';
