name: "Setup Environment"
description: "Setup Node.js, pnpm and dependencies with caching"

inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "22"
  playwright:
    description: "Install Playwright browsers"
    required: false
    default: "false"
  frozen-lockfile:
    description: "Use frozen lockfile"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js and cache pnpm store
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: |
        # Use frozen-lockfile by default unless explicitly set to false
        if [[ "${{ inputs.frozen-lockfile }}" == "false" ]]; then
          echo "Installing dependencies without frozen lockfile..."
          pnpm install --no-frozen-lockfile
        else
          echo "Installing dependencies with frozen lockfile..."
          pnpm install --frozen-lockfile
        fi

    # Step 4: (Optional) Get Playwright version and set cache path
    - name: Get Playwright version
      if: inputs.playwright == 'true'
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm list playwright-chromium --depth 0 --json 2>/dev/null | jq -r 'if type == "array" then .[0].devDependencies["playwright-chromium"].version else .devDependencies["playwright-chromium"].version end' 2>/dev/null || echo "1.55.0")
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
        echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright" >> $GITHUB_ENV
        echo "Playwright version: $PLAYWRIGHT_VERSION"
        echo "Browsers cache path: $HOME/.cache/playwright"

    # Step 5: (Optional) Cache Playwright browsers
    - name: Cache Playwright browsers
      if: inputs.playwright == 'true'
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
        key: playwright-${{ runner.os }}-v2-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          playwright-${{ runner.os }}-v2-

    # Step 6: (Optional) Install Playwright browsers (if cache miss)
    - name: Install Playwright browsers
      if: inputs.playwright == 'true' && steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing Playwright browsers (cache miss)..."
        pnpm exec playwright install chromium --with-deps

    # Step 7: (Optional) Verify Playwright installation
    - name: Verify Playwright installation
      if: inputs.playwright == 'true'
      shell: bash
      run: |
        if [ "${{ steps.playwright-cache.outputs.cache-hit }}" == "true" ]; then
          echo "✅ Playwright browsers restored from cache"
        else
          echo "✅ Playwright browsers installed"
        fi
        ls -la ${{ env.PLAYWRIGHT_BROWSERS_PATH }} || echo "Cache directory not found"
