/**
 * MCP (Model Context Protocol) server implementation for VitePress build data.
 * This file contains complex protocol handling and data transformation logic
 * that legitimately requires high line count due to the nature of MCP operations.
 */
/* eslint-disable max-lines */
import type { Writable } from 'node:stream';
import { fileURLToPath } from 'node:url';
import type {
  SiteDevToolsBuildArtifactSnapshot,
  SiteDevToolsBuildComponentSummary,
  SiteDevToolsBuildDataOptions,
  SiteDevToolsBuildOverview,
  SiteDevToolsBuildPageSummary,
  SiteDevToolsBuildReportPayload,
} from './build-data';
import { SiteDevToolsBuildDataStore } from './build-data';

type JsonRpcId = number | string | null;

interface JsonRpcRequest {
  id?: JsonRpcId;
  jsonrpc: '2.0';
  method: string;
  params?: unknown;
}

interface JsonRpcResponse {
  error?: {
    code: number;
    message: string;
  };
  id: JsonRpcId;
  jsonrpc: '2.0';
  result?: unknown;
}

interface SiteDevToolsBuildMcpResource {
  description: string;
  mimeType: 'text/markdown';
  name: string;
  text: string;
  uri: string;
}

interface SiteDevToolsBuildMcpToolStringSchema {
  enum?: readonly string[];
  type: 'string';
}

interface SiteDevToolsBuildMcpToolInputSchema {
  additionalProperties: false;
  properties: Record<string, SiteDevToolsBuildMcpToolStringSchema>;
  required?: readonly string[];
  type: 'object';
}

type SiteDevToolsBuildToolArguments = Record<string, string | undefined>;

interface SiteDevToolsBuildMcpToolDefinition {
  description: string;
  execute: (
    dataStore: SiteDevToolsBuildDataStore,
    args: SiteDevToolsBuildToolArguments,
  ) => Promise<SiteDevToolsBuildMcpToolResult> | SiteDevToolsBuildMcpToolResult;
  inputSchema: SiteDevToolsBuildMcpToolInputSchema;
  name: SiteDevToolsBuildMcpToolName;
  validate?: (args: SiteDevToolsBuildToolArguments) => void;
}

class JsonRpcRequestError extends Error {
  declare readonly code: number;
  declare readonly id: JsonRpcId;

  constructor(code: number, message: string, id: JsonRpcId = null) {
    super(message);
    this.name = 'JsonRpcRequestError';
    Object.defineProperty(this, 'code', {
      configurable: true,
      value: code,
      writable: true,
    });
    Object.defineProperty(this, 'id', {
      configurable: true,
      value: id,
      writable: true,
    });
  }
}

export type SiteDevToolsBuildMcpToolName =
  | 'get_artifact'
  | 'get_build_overview'
  | 'get_build_report'
  | 'get_component'
  | 'get_page'
  | 'list_pages';

export interface SiteDevToolsBuildMcpServerOptions
  extends SiteDevToolsBuildDataOptions {
  stderr?: Writable;
  stdin?: NodeJS.ReadableStream;
  stdout?: Writable;
}

type SiteDevToolsBuildMcpToolResult =
  | SiteDevToolsBuildArtifactSnapshot
  | SiteDevToolsBuildComponentSummary
  | {
      error: string;
    }
  | SiteDevToolsBuildOverview
  | SiteDevToolsBuildPageSummary[]
  | SiteDevToolsBuildReportPayload
  | {
      page: unknown;
      summary: SiteDevToolsBuildPageSummary;
    };

const JSON_RPC_VERSION = '2.0' as const;
const JSON_RPC_PARSE_ERROR = -32_700;
const JSON_RPC_INVALID_REQUEST = -32_600;
const JSON_RPC_METHOD_NOT_FOUND = -32_601;
const JSON_RPC_INVALID_PARAMS = -32_602;
const JSON_RPC_INTERNAL_ERROR = -32_603;
const CONTENT_LENGTH_HEADER_NAME = 'content-length';
const CONTENT_LENGTH_HEADER_TOKEN = `${CONTENT_LENGTH_HEADER_NAME}:`;

const SERVER_NAME = 'docs-islands-site-devtools-build-mcp';
const SERVER_VERSION = '1.0.0';
const PROTOCOL_VERSION = '2024-11-05';
const HELP_TEXT = `
Usage:
  docs-islands-vitepress-site-devtools-mcp --outDir <path> [--assetsDir <dir>]

Options:
  --outDir     Built docs output directory. Required.
  --assetsDir  Assets directory name inside outDir. Defaults to "assets".
  --help       Show this message.
`.trim();

const createToolInputSchema = ({
  properties,
  required,
}: {
  properties: SiteDevToolsBuildMcpToolInputSchema['properties'];
  required?: readonly string[];
}): SiteDevToolsBuildMcpToolInputSchema => ({
  additionalProperties: false,
  ...(required && required.length > 0 ? { required } : {}),
  properties,
  type: 'object',
});

const MCP_RESOURCES: SiteDevToolsBuildMcpResource[] = [
  {
    description:
      'Overview of the build-time data exposed by the Site DevTools MCP server.',
    mimeType: 'text/markdown',
    name: 'site-devtools-build-data-overview',
    text: [
      '# Site DevTools Build Data Overview',
      '',
      'This MCP server exposes build-time data generated by docs-islands Site DevTools instrumentation.',
      '',
      'Available data:',
      '- Page metafile manifest',
      '- Per-page page metafile JSON payloads',
      '- Component build metrics',
      '- Artifact snapshots shaped like the shared AI prompt context',
      '- Build-time AI report JSON payloads',
      '',
      'This server does not read browser runtime state and does not invoke AI providers.',
    ].join('\n'),
    uri: 'file://docs-islands/site-devtools-build-data-overview.md',
  },
  {
    description:
      'Recommended tool usage flow for exploring docs-islands build artifacts.',
    mimeType: 'text/markdown',
    name: 'site-devtools-build-tool-guide',
    text: [
      '# Site DevTools Build Tool Guide',
      '',
      'Recommended exploration flow:',
      '1. Call `get_build_overview` to confirm the loaded build.',
      '2. Call `list_pages` to find available page IDs.',
      '3. Call `get_page` for a specific page.',
      '4. Call `get_component` for a component on that page.',
      '5. Call `get_artifact` for a chunk or module artifact snapshot.',
      '6. Call `get_build_report` to inspect a saved AI report payload when needed.',
      '',
      'Stable identifiers:',
      '- Pages use `pageId`.',
      '- Components use `pageId + componentName`.',
      '- Chunk artifacts use `artifactKind + displayPath`.',
      '- Module artifacts use `artifactKind + displayPath` or `file + moduleId`.',
      '- Build reports use `reportId` or `artifactKey`.',
    ].join('\n'),
    uri: 'file://docs-islands/site-devtools-build-tool-guide.md',
  },
];

const MCP_TOOL_DEFINITIONS = [
  {
    description:
      'Return build ID, page count, component count, total bundle bytes, and whether AI reports exist.',
    execute: (dataStore: SiteDevToolsBuildDataStore) =>
      dataStore.getBuildOverview(),
    inputSchema: createToolInputSchema({
      properties: {},
    }),
    name: 'get_build_overview',
  },
  {
    description:
      'List all page IDs with their page metafile references and summary metadata.',
    execute: (dataStore: SiteDevToolsBuildDataStore) => dataStore.listPages(),
    inputSchema: createToolInputSchema({
      properties: {},
    }),
    name: 'list_pages',
  },
  {
    description:
      'Return the page metafile payload and summary for a single page ID.',
    execute: (
      dataStore: SiteDevToolsBuildDataStore,
      args: SiteDevToolsBuildToolArguments,
    ) => dataStore.getPage(args.pageId!),
    inputSchema: createToolInputSchema({
      properties: {
        pageId: {
          type: 'string',
        },
      },
      required: ['pageId'],
    }),
    name: 'get_page',
  },
  {
    description:
      'Return a component build metric by page ID and component name.',
    execute: (
      dataStore: SiteDevToolsBuildDataStore,
      args: SiteDevToolsBuildToolArguments,
    ) => dataStore.getComponent(args.pageId!, args.componentName!),
    inputSchema: createToolInputSchema({
      properties: {
        componentName: {
          type: 'string',
        },
        pageId: {
          type: 'string',
        },
      },
      required: ['pageId', 'componentName'],
    }),
    name: 'get_component',
  },
  {
    description:
      'Return a shared prompt snapshot for a chunk or module artifact.',
    execute: (
      dataStore: SiteDevToolsBuildDataStore,
      args: SiteDevToolsBuildToolArguments,
    ) =>
      dataStore.getArtifact({
        artifactKind:
          args.artifactKind as SiteDevToolsBuildArtifactSnapshot['artifactKind'],
        displayPath: args.displayPath,
        file: args.file,
        moduleId: args.moduleId,
      }),
    inputSchema: createToolInputSchema({
      properties: {
        artifactKind: {
          enum: ['bundle-chunk', 'bundle-module'],
          type: 'string',
        },
        displayPath: {
          type: 'string',
        },
        file: {
          type: 'string',
        },
        moduleId: {
          type: 'string',
        },
      },
      required: ['artifactKind'],
    }),
    name: 'get_artifact',
    validate: (args: SiteDevToolsBuildToolArguments) => {
      if (args.artifactKind === 'bundle-chunk') {
        if (!args.displayPath) {
          throw new Error(
            'Provide "displayPath" for "bundle-chunk" artifact lookups.',
          );
        }

        if (args.file || args.moduleId) {
          throw new Error(
            '"bundle-chunk" artifact lookups only support "displayPath".',
          );
        }

        return;
      }

      if ((args.file && !args.moduleId) || (!args.file && args.moduleId)) {
        throw new Error(
          'Provide both "file" and "moduleId" together for "bundle-module" lookups.',
        );
      }

      if (!args.displayPath && !args.file && !args.moduleId) {
        throw new Error(
          'Provide "displayPath" or both "file" and "moduleId" for "bundle-module" artifact lookups.',
        );
      }
    },
  },
  {
    description:
      'Return a saved build-time AI report payload by report ID or artifact key.',
    execute: (
      dataStore: SiteDevToolsBuildDataStore,
      args: SiteDevToolsBuildToolArguments,
    ) =>
      dataStore.getBuildReport({
        artifactKey: args.artifactKey,
        reportId: args.reportId,
      }),
    inputSchema: createToolInputSchema({
      properties: {
        artifactKey: {
          type: 'string',
        },
        reportId: {
          type: 'string',
        },
      },
    }),
    name: 'get_build_report',
    validate: (args: SiteDevToolsBuildToolArguments) => {
      if (!args.artifactKey && !args.reportId) {
        throw new Error('Provide at least one of "reportId" or "artifactKey".');
      }
    },
  },
] as const satisfies readonly SiteDevToolsBuildMcpToolDefinition[];

const MCP_TOOLS = MCP_TOOL_DEFINITIONS.map(
  ({ description, inputSchema, name }) => ({
    description,
    inputSchema,
    name,
  }),
);

const isRecord = (value: unknown): value is Record<string, unknown> =>
  Boolean(value && typeof value === 'object' && !Array.isArray(value));

const isJsonRpcId = (value: unknown): value is JsonRpcId =>
  value === null || typeof value === 'number' || typeof value === 'string';

const getMessageId = (value: unknown): JsonRpcId =>
  isRecord(value) && isJsonRpcId(value.id) ? value.id : null;

const getErrorMessage = (error: unknown, fallback: string) =>
  error instanceof Error ? error.message : fallback;

const formatQuotedValues = (values: readonly string[]) =>
  values.map((value) => `"${value}"`).join(', ');

const createJsonRpcErrorResponse = (
  id: JsonRpcId,
  code: number,
  message: string,
): JsonRpcResponse => ({
  error: {
    code,
    message,
  },
  id,
  jsonrpc: JSON_RPC_VERSION,
});

const createJsonRpcSuccessResponse = (
  id: JsonRpcId,
  result: unknown,
): JsonRpcResponse => ({
  id,
  jsonrpc: JSON_RPC_VERSION,
  result,
});

const createJsonRpcErrorFromUnknown = (
  error: unknown,
  fallbackId: JsonRpcId = null,
): JsonRpcResponse => {
  if (error instanceof JsonRpcRequestError) {
    return createJsonRpcErrorResponse(error.id, error.code, error.message);
  }

  return createJsonRpcErrorResponse(
    fallbackId,
    JSON_RPC_INTERNAL_ERROR,
    getErrorMessage(error, 'Internal error.'),
  );
};

const serializeToolResult = (
  result: SiteDevToolsBuildMcpToolResult,
  isError = false,
) => ({
  content: [
    {
      text: JSON.stringify(result, null, 2),
      type: 'text',
    },
  ],
  ...(isError ? { isError: true } : {}),
  structuredContent: result,
});

const validateToolArguments = ({
  args,
  schema,
  toolName,
}: {
  args: unknown;
  schema: SiteDevToolsBuildMcpToolInputSchema;
  toolName: SiteDevToolsBuildMcpToolName;
}): SiteDevToolsBuildToolArguments => {
  const source = args === undefined ? {} : args;

  if (!isRecord(source)) {
    throw new Error(`Tool "${toolName}" arguments must be an object.`);
  }

  const allowedKeys = new Set(Object.keys(schema.properties));
  const unknownKeys = Object.keys(source).filter(
    (key) => !allowedKeys.has(key),
  );

  if (schema.additionalProperties === false && unknownKeys.length > 0) {
    throw new Error(
      `Unknown argument${unknownKeys.length === 1 ? '' : 's'}: ${formatQuotedValues(unknownKeys)}.`,
    );
  }

  const requiredKeys = new Set(schema.required);
  const normalizedArgs: SiteDevToolsBuildToolArguments = {};

  for (const [key, propertySchema] of Object.entries(schema.properties)) {
    const nextValue = source[key];

    if (nextValue === undefined) {
      if (requiredKeys.has(key)) {
        throw new Error(`"${key}" must be a non-empty string.`);
      }

      normalizedArgs[key] = undefined;
      continue;
    }

    if (typeof nextValue !== 'string' || nextValue.length === 0) {
      throw new Error(
        requiredKeys.has(key)
          ? `"${key}" must be a non-empty string.`
          : `"${key}" must be a non-empty string when provided.`,
      );
    }

    if (propertySchema.enum && !propertySchema.enum.includes(nextValue)) {
      throw new Error(
        `"${key}" must be one of ${formatQuotedValues(propertySchema.enum)}.`,
      );
    }

    normalizedArgs[key] = nextValue;
  }

  return normalizedArgs;
};

const validateJsonRpcRequest = (message: unknown): JsonRpcRequest => {
  const fallbackId = getMessageId(message);

  if (!isRecord(message)) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_REQUEST,
      'Request must be an object.',
    );
  }

  if ('id' in message && !isJsonRpcId(message.id)) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_REQUEST,
      '"id" must be a string, number, or null when provided.',
    );
  }

  if (message.jsonrpc !== JSON_RPC_VERSION) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_REQUEST,
      `"jsonrpc" must be "${JSON_RPC_VERSION}".`,
      fallbackId,
    );
  }

  if (typeof message.method !== 'string' || message.method.length === 0) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_REQUEST,
      '"method" must be a non-empty string.',
      fallbackId,
    );
  }

  const normalizedId = isJsonRpcId(message.id) ? message.id : undefined;

  return {
    id: normalizedId,
    jsonrpc: JSON_RPC_VERSION,
    method: message.method,
    params: message.params,
  };
};

const getRequiredRequestRecord = (
  params: unknown,
  method: string,
  id: JsonRpcId,
): Record<string, unknown> => {
  if (!isRecord(params)) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_PARAMS,
      `Method "${method}" requires object params.`,
      id,
    );
  }

  return params;
};

const getRequiredRequestString = (
  value: Record<string, unknown>,
  key: string,
  id: JsonRpcId,
): string => {
  const nextValue = value[key];

  if (typeof nextValue !== 'string' || nextValue.length === 0) {
    throw new JsonRpcRequestError(
      JSON_RPC_INVALID_PARAMS,
      `"${key}" must be a non-empty string.`,
      id,
    );
  }

  return nextValue;
};

const createToolArgumentErrorResult = (message: string) =>
  serializeToolResult(
    {
      error: message,
    },
    true,
  );

const getRequiredCliOptionValue = (
  argv: string[],
  index: number,
  flag: string,
) => {
  const value = argv[index + 1];

  if (!value) {
    throw new Error(`Missing value for ${flag}`);
  }

  return value;
};

const parseCliArgs = (argv: string[]): SiteDevToolsBuildDataOptions | null => {
  const nextOptions: SiteDevToolsBuildDataOptions = {
    outDir: '',
  };

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];

    if (argument === '--help') {
      return null;
    }

    if (argument === '--outDir') {
      nextOptions.outDir = getRequiredCliOptionValue(argv, index, '--outDir');
      index += 1;
      continue;
    }

    if (argument === '--assetsDir') {
      nextOptions.assetsDir = getRequiredCliOptionValue(
        argv,
        index,
        '--assetsDir',
      );
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument: ${argument}`);
  }

  if (!nextOptions.outDir) {
    throw new Error('Missing required argument: --outDir');
  }

  return nextOptions;
};

export interface SiteDevToolsBuildMcpServer {
  close: () => void;
  handleMessage: (message: unknown) => Promise<JsonRpcResponse | null>;
  listen: () => void;
}

export const createSiteDevToolsBuildMcpServer = (
  options: SiteDevToolsBuildMcpServerOptions,
): SiteDevToolsBuildMcpServer => {
  const dataStore = new SiteDevToolsBuildDataStore(options);
  const stdin = options.stdin || process.stdin;
  const stdout = options.stdout || process.stdout;
  const stderr = options.stderr || process.stderr;
  let buffer = Buffer.alloc(0);
  let closed = false;
  let listening = false;
  let onData: ((chunk: Buffer | string) => void) | null = null;

  const writeMessage = (message: JsonRpcResponse) => {
    if (closed) {
      return;
    }

    const payload = Buffer.from(JSON.stringify(message), 'utf8');
    stdout.write(
      `Content-Length: ${payload.byteLength}\r\nContent-Type: application/json\r\n\r\n`,
    );
    stdout.write(payload);
  };

  const writeTransportError = (message: string) => {
    stderr.write(`${message}\n`);
  };

  const detachListener = () => {
    if (!listening || !onData) {
      return;
    }

    stdin.off('data', onData);
    listening = false;
  };

  const closeServer = () => {
    closed = true;
    buffer = Buffer.alloc(0);
    detachListener();
  };

  const resyncBuffer = (searchFrom: number) => {
    const nextHeaderIndex = buffer
      .toString('utf8')
      .toLowerCase()
      .indexOf(CONTENT_LENGTH_HEADER_TOKEN, searchFrom);

    buffer =
      nextHeaderIndex === -1 ? Buffer.alloc(0) : buffer.slice(nextHeaderIndex);
  };

  const handleToolCall = async (
    tool: SiteDevToolsBuildMcpToolDefinition,
    args: unknown,
  ) => {
    try {
      const normalizedArgs = validateToolArguments({
        args,
        schema: tool.inputSchema,
        toolName: tool.name,
      });
      tool.validate?.(normalizedArgs);
      return serializeToolResult(await tool.execute(dataStore, normalizedArgs));
    } catch (error) {
      return createToolArgumentErrorResult(
        getErrorMessage(error, 'Tool execution failed.'),
      );
    }
  };

  const handleRequest = async (
    request: JsonRpcRequest,
  ): Promise<JsonRpcResponse | null> => {
    const id = request.id ?? null;

    switch (request.method) {
      case 'initialize': {
        return createJsonRpcSuccessResponse(id, {
          capabilities: {
            resources: {
              listChanged: false,
              subscribe: false,
            },
            tools: {
              listChanged: false,
            },
          },
          protocolVersion: PROTOCOL_VERSION,
          serverInfo: {
            name: SERVER_NAME,
            version: SERVER_VERSION,
          },
        });
      }
      case 'notifications/initialized': {
        return null;
      }
      case 'ping': {
        return createJsonRpcSuccessResponse(id, {});
      }
      case 'tools/list': {
        return createJsonRpcSuccessResponse(id, {
          tools: MCP_TOOLS,
        });
      }
      case 'tools/call': {
        const params = getRequiredRequestRecord(
          request.params,
          'tools/call',
          id,
        );
        const toolName = getRequiredRequestString(params, 'name', id);
        const tool = MCP_TOOL_DEFINITIONS.find(
          (item) => item.name === toolName,
        );

        if (!tool) {
          return createJsonRpcSuccessResponse(
            id,
            createToolArgumentErrorResult(`Unknown tool: ${toolName}`),
          );
        }

        return createJsonRpcSuccessResponse(
          id,
          await handleToolCall(tool, params.arguments),
        );
      }
      case 'resources/list': {
        return createJsonRpcSuccessResponse(id, {
          resources: MCP_RESOURCES.map((resource) => ({
            description: resource.description,
            mimeType: resource.mimeType,
            name: resource.name,
            uri: resource.uri,
          })),
        });
      }
      case 'resources/read': {
        const params = getRequiredRequestRecord(
          request.params,
          'resources/read',
          id,
        );
        const resourceUri = getRequiredRequestString(params, 'uri', id);
        const resource = MCP_RESOURCES.find((item) => item.uri === resourceUri);

        if (!resource) {
          throw new JsonRpcRequestError(
            JSON_RPC_INVALID_PARAMS,
            `Unknown resource URI: ${resourceUri}`,
            id,
          );
        }

        return createJsonRpcSuccessResponse(id, {
          contents: [
            {
              mimeType: resource.mimeType,
              text: resource.text,
              uri: resource.uri,
            },
          ],
        });
      }
      case 'shutdown': {
        return createJsonRpcSuccessResponse(id, null);
      }
      case 'exit': {
        closeServer();
        return null;
      }
      default: {
        if (request.id === undefined) {
          return null;
        }

        return createJsonRpcErrorResponse(
          id,
          JSON_RPC_METHOD_NOT_FOUND,
          `Method not found: ${request.method}`,
        );
      }
    }
  };

  const handleIncomingMessage = async (
    message: unknown,
  ): Promise<JsonRpcResponse | null> => {
    const fallbackId = getMessageId(message);

    try {
      return await handleRequest(validateJsonRpcRequest(message));
    } catch (error) {
      return createJsonRpcErrorFromUnknown(error, fallbackId);
    }
  };

  const flushBuffer = async () => {
    while (true) {
      const headerEnd = buffer.indexOf('\r\n\r\n');

      if (headerEnd === -1) {
        return;
      }

      const headerText = buffer.slice(0, headerEnd).toString('utf8');
      const headers = Object.fromEntries(
        headerText
          .split('\r\n')
          .map((line) => line.split(/:\s*/, 2))
          .filter(
            (entry): entry is [string, string] =>
              entry.length === 2 &&
              typeof entry[0] === 'string' &&
              typeof entry[1] === 'string',
          )
          .map(([key, value]) => [key.toLowerCase(), value]),
      );
      const contentLength = Number.parseInt(
        headers[CONTENT_LENGTH_HEADER_NAME],
        10,
      );

      if (!Number.isFinite(contentLength) || contentLength < 0) {
        writeTransportError('Missing or invalid Content-Length header.');
        writeMessage(
          createJsonRpcErrorResponse(
            null,
            JSON_RPC_PARSE_ERROR,
            'Parse error.',
          ),
        );
        resyncBuffer(headerEnd + 4);
        continue;
      }

      const messageStart = headerEnd + 4;
      const messageEnd = messageStart + contentLength;

      if (buffer.byteLength < messageEnd) {
        return;
      }

      const payload = buffer.slice(messageStart, messageEnd).toString('utf8');
      buffer = buffer.slice(messageEnd);

      let message: unknown;

      try {
        message = JSON.parse(payload) as JsonRpcRequest;
      } catch {
        writeTransportError('Invalid JSON payload.');
        writeMessage(
          createJsonRpcErrorResponse(
            null,
            JSON_RPC_PARSE_ERROR,
            'Parse error.',
          ),
        );
        continue;
      }

      const response = await handleIncomingMessage(message);

      if (response) {
        writeMessage(response);
      }
    }
  };

  let pendingFlush = Promise.resolve();

  onData = (chunk: Buffer | string) => {
    if (closed) {
      return;
    }

    buffer = Buffer.concat([
      buffer,
      Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk),
    ]);
    pendingFlush = pendingFlush
      .then(() => flushBuffer())
      .catch((error) => {
        writeTransportError(getErrorMessage(error, 'MCP transport error.'));
        buffer = Buffer.alloc(0);
      });
  };

  return {
    close() {
      closeServer();
    },
    async handleMessage(message: unknown) {
      return handleIncomingMessage(message);
    },
    listen() {
      if (closed || listening || !onData) {
        return;
      }

      stdin.on('data', onData);
      listening = true;
    },
  };
};

export const startSiteDevToolsBuildMcpServer = (
  options: SiteDevToolsBuildMcpServerOptions,
): SiteDevToolsBuildMcpServer => {
  const server = createSiteDevToolsBuildMcpServer(options);
  server.listen();
  return server;
};

export const runSiteDevToolsBuildMcpCli = async (
  argv: string[] = process.argv.slice(2),
): Promise<void> => {
  try {
    const options = parseCliArgs(argv);

    if (!options) {
      process.stdout.write(`${HELP_TEXT}\n`);
      return;
    }

    startSiteDevToolsBuildMcpServer(options);
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : 'Failed to start MCP server.'}\n`,
    );
    process.stderr.write(`${HELP_TEXT}\n`);
    process.exitCode = 1;
  }
};

const currentFilePath = fileURLToPath(import.meta.url);

if (process.argv[1] && process.argv[1] === currentFilePath) {
  runSiteDevToolsBuildMcpCli().catch((error) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : 'Failed to start MCP server.'}\n`,
    );
    process.exitCode = 1;
  });
}

export type {
  SiteDevToolsBuildArtifactSnapshot,
  SiteDevToolsBuildComponentSummary,
  SiteDevToolsBuildDataOptions,
  SiteDevToolsBuildOverview,
  SiteDevToolsBuildPageSummary,
  SiteDevToolsBuildReportPayload,
} from './build-data';
